### ISSUE TITLE
RAS container

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/wat-api#22]

**Comment by HenryGeorgist** [comment]
https://github.com/USACE/rasrun-test

**Comment by HenryGeorgist** [comment]
needs to be updated to use payload.yml as the input argument

**Comment by HenryGeorgist** [comment]
aside from this "ras-runner" container, we need a "ras-mutator" that allows for mutation of input files (e.g. the input hdf and .**X files)

**Comment by slawler** [comment]
Functional prototypes for the ras containers are documented and available here:

[ras-unsteady](https://hub.docker.com/repository/docker/lawlerseth/ras-unsteady): runs an unsteady compute given a payload as described in the container docs.

[ras-mutator](https://hub.docker.com/repository/docker/lawlerseth/ras-mutator): currently updates the `*.tmp.hdf` file for 2D unsteady models given a payload as described in the container docs. Needs to be updated to overwrite the `.b*` file for unsteady 1D model boundary conditions.
