### ISSUE TITLE
Flesh out design for input and output and linkedinput

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/wat-api#26]
we need to think through what the minimum set of information to describe an input an output and a linkedinput are so that we can begin to link more complicated models.

**Comment by slawler** [comment]
Looking at this today. I'll start by reviewing the [manifests / payloads](https://github.com/USACE/wat-api/tree/main/configs) against what the plugins currently need / may need. If  we can land on a consistent set for this phase of development, the AWS-Batch testing will be the beneficiary.

**Comment by HenryGeorgist** [comment]
solved with wat-go-sdk plugin manager
