### ISSUE TITLE
mock sqs with elasticmq

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/wat-api#27]
https://smartscribs.com/emulate-aws-sqs-offline/

**Comment by slawler** [comment]
Copied the sandbox I created locally a few weeks ago here: [cloud-wat-sandbox](https://github.com/slawler/cloud-wat-sandbox).

Should work out of the box, there is a postman collection file to test with. Let me know if you have any issues.

**Comment by HenryGeorgist** [comment]
addressed with a157f5735
