### ISSUE TITLE
create a ras-mutator plugin

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/wat-api#38]
in order to increase modularity of the processes included in any workflow in wat we want to separate the preprocessing, processing, and post processing of most applications.  The ras-mutator will be responsible for two activities:
1. move the necessary files from the base storage location to an area where files can be uniquely changed
2. change the model files to create a unique run for the model

**Comment by slawler** [comment]
Completed in #22

**Comment by HenryGeorgist** [comment]
@slawler should we create a new ticket to track the update to include the b** file for 1d boundary conditions?
